package cachet.model;
// Generated May 21, 2010 6:31:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * App generated by hbm2java
 */
public class App  implements java.io.Serializable {


     private Integer appId;
     private String name;
     private String description;
     private Date updated;

    public App() {
    }

    public App(String name, String description, Date updated) {
       this.name = name;
       this.description = description;
       this.updated = updated;
    }
   
    public Integer getAppId() {
        return this.appId;
    }
    
    public void setAppId(Integer appId) {
        this.appId = appId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


