package cachet.model;
// Generated May 21, 2010 6:31:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PersonApp generated by hbm2java
 */
public class PersonApp  implements java.io.Serializable {


     private PersonAppId id;
     private Date updated;

    public PersonApp() {
    }

	
    public PersonApp(PersonAppId id) {
        this.id = id;
    }
    public PersonApp(PersonAppId id, Date updated) {
       this.id = id;
       this.updated = updated;
    }
   
    public PersonAppId getId() {
        return this.id;
    }
    
    public void setId(PersonAppId id) {
        this.id = id;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


