package cachet.model;
// Generated May 21, 2010 6:31:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PersonState generated by hbm2java
 */
public class PersonState  implements java.io.Serializable {


     private Integer personId;
     private String status;
     private Date updated;

    public PersonState() {
    }

    public PersonState(String status, Date updated) {
       this.status = status;
       this.updated = updated;
    }
   
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


