package cachet.model;
// Generated May 21, 2010 6:31:20 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PersonWallId generated by hbm2java
 */
public class PersonWallId  implements java.io.Serializable {


     private String personId;
     private String friendId;
     private Date created;

    public PersonWallId() {
    }

    public PersonWallId(String personId, String friendId, Date created) {
       this.personId = personId;
       this.friendId = friendId;
       this.created = created;
    }
   
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }
    public String getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(String friendId) {
        this.friendId = friendId;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonWallId) ) return false;
		 PersonWallId castOther = ( PersonWallId ) other; 
         
		 return ( (this.getPersonId()==castOther.getPersonId()) || ( this.getPersonId()!=null && castOther.getPersonId()!=null && this.getPersonId().equals(castOther.getPersonId()) ) )
 && ( (this.getFriendId()==castOther.getFriendId()) || ( this.getFriendId()!=null && castOther.getFriendId()!=null && this.getFriendId().equals(castOther.getFriendId()) ) )
 && ( (this.getCreated()==castOther.getCreated()) || ( this.getCreated()!=null && castOther.getCreated()!=null && this.getCreated().equals(castOther.getCreated()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPersonId() == null ? 0 : this.getPersonId().hashCode() );
         result = 37 * result + ( getFriendId() == null ? 0 : this.getFriendId().hashCode() );
         result = 37 * result + ( getCreated() == null ? 0 : this.getCreated().hashCode() );
         return result;
   }   


}


